port = 50242
server_root = "app"
schema_source = "./schemas.json"
allow_origins = ["http://localhost:9000"]
user_agent = "curl/7.54.1"
resources = [
 "index.html",
 "js/",
 "css/",
 "favicon.ico"
]
writable_resources = [
    "css/thing.txt"
]
[headers.Global]
Server = "Webserver"

[headers."text/html"]
Cross-Origin-Opener-Policy = "same-origin"
Cross-Origin-Embedder-Policy = "credentialless"
Cross-Origin-Resource-Policy = "cross-origin"

[headers."text/css"]
Server = "cssserver"

[headers."application/json"]
Access-Control-Allow-Origin = "@Origin"
Vary = "Origin"

[api_required_headers]
x-custom-header = "a123"

[remote_resources]
thing = { url = "http://example.com" }
bad = { url = ":example.com" }

[apis]
test = { command = "testi", method = "get" }
update = { command = "update", method = "get" }

[apis.version]
require_headers = { test-header = "hello", x-custom-header = "a124", invalid-header = [1] }
method = "post"
response = { value = "{\"data\": \"Hello world!\"}", code = 200, type = "application/json" }

[remote_resources.update]
url = "http://127.0.0.1:9000/example_target.json"
key_header = "x-custom-header"
key_value = "FbUQdcS6ZFXnWKJc8hQu8K+YkKKhbEOI0aMxEGAjqS7EZC1o"
schema = "test"
file_targets = "./app/data/stored.json"
model = "json"
request_method = "GET"
forward_queries = ["search"]

[remote_resources.testi]
url = "http://127.0.0.1:9000/api/version"
key_header = "x-custom-header"
key_value = "plain header value"
key_mode = "plain"
model = "json"
request_method = "POST"